const express = require("express");
router = express.Router();
const Registration = require("../controllers/Registration");
const Auth = require("../middlewares/Auth");
const Login = require("../controllers/Login");
const Logout = require("../controllers/Logout");
const Chat = require("../controllers/Chat");
const CreateRoom = require("../controllers/CreateRoom");
const JoinRoom = require("../controllers/JoinRoom");
const checkAuthentication = require("../controllers/checkAuthentication");
router.post("/", Auth, checkAuthentication);
router.post("/register", Registration);
router.post("/login", Login);
router.post("/logout", Logout);
router.post("/chat", Auth, Chat);
router.post("/create_room", Auth, CreateRoom);
router.post("/join_room", Auth, JoinRoom);
module.exports = router;
